### ISSUE TITLE
Add init to subcommands

### ISSUE THREAD

**Issue by technetos** [CachedNerds/Hatch#13]
As a user I want to be able to create the files needed to use tup.

**Comment by DannyPeck** [comment]
What do you imagine the different is between init and new and how will the typical workflow of a user making a new project look?

**Comment by technetos** [comment]
The current design is somewhat undecided as to whether we want to have the content of the various tup related files IN the source code for hatch or as template files stored somewhere.  

If we decide we want to use template files then init will be used to install template files wherever we want to have them stored.

**Comment by DannyPeck** [comment]
We have deprecated this command with the combination of the new command and auto generating the assets.
