### ISSUE TITLE
Add platform detection

### ISSUE THREAD

**Issue by technetos** [CachedNerds/Hatch#15]
As a user I would like hatch to auto-detect the platform I am currently building on.

**Comment by DannyPeck** [comment]
I have found a Rust crate named [os_type](https://github.com/schultyy/os_type) that automatically detects the operating system; however, it is not quite complete.  It is missing Windows support but there is a PR open with Windows support.  We could potentially fork this project, clean it up and use it ourselves.

**Comment by DannyPeck** [comment]
I have found a fork of this project that is more maintained that os_type named [os_info](https://github.com/DarkEld3r/os_info) which has the additional windows support we want and also only selectively compiles the platforms the user is using.  There was a bug in the macos support and I have opened a PR to fix this issue.
