### ISSUE TITLE
Update Cli to support dependency specifications

### ISSUE THREAD

**Issue by technetos** [CachedNerds/Hatch#20]

**Comment by DannyPeck** [comment]
What do you mean exactly by dependency specifications?

**Comment by technetos** [comment]
```Bash
hatch new AwesomeProject --include @CachedNerds/Toolbox:branch @CachedNerds/Falcon
```
would pull in those repos and set them up as dependencies for that project, and add / update the hatch.yml file

**Comment by xmclark** [comment]
How about npm style using install command? e.g. `hatch install CachedNerds/Toolbox:master`
