### ISSUE TITLE
Add testing support for Hatch

### ISSUE THREAD

**Issue by technetos** [CachedNerds/Hatch#24]

**Comment by xmclark** [comment]
Can we clarify what this means? My first thought was running tests associated with a Hatch project e.g. `hatch test` and getting test results in output.

**Comment by DannyPeck** [comment]
I am interpreting this to mean running the tests of a given project.  The test command will take a list of project names and run their tests in order, printing their output to the console.  Here is an example: 
```
hatch test Option Sink
```
  On a side note, what is the behavior for operations that assume that a project is built?

**Comment by DannyPeck** [comment]
The command will accept 0 or more projects which will be space delimited.  If the user provides 0 projects then Hatch will execute all tests.

**Comment by DannyPeck** [comment]
Actually, if we decide to split up the Toolbox, then does having multiple project support make sense anymore?

**Comment by technetos** [comment]
not really

**Comment by DannyPeck** [comment]
To state the current design for this issue, the test command will be responsible for executing the tests for a single project.

**Comment by technetos** [comment]
I originally had envisioned this issue to be for unit tests that test **Hatch**

**Comment by DannyPeck** [comment]
I didn't realize that due to the wording "support" made me think it was referring to adding the ability to test the projects.  We should probably just create another ticket for adding unit tests to Hatch.

**Comment by xmclark** [comment]
If testing support is only for Hatch, then I'm not sure what needs to be done. Cargo comes with a test runner.
