### ISSUE TITLE
Implement Dependency Registry

### ISSUE THREAD

**Issue by DannyPeck** [CachedNerds/Hatch#57]
In order to avoid processing duplicate dependencies within our projects we will create a dependency registry.  This registry will ensure that only a single instance of a dependency exists and that all projects that wish to depend on it will depend on this single instance.  This will allow us to not duplicate dependencies.  This registry will exist at the top level of the project structure and both the project and its dependencies can point to this location.

**Comment by technetos** [comment]
If we add path tracking to project we can make the registry relative to the root project. #51
