### ISSUE TITLE
The hatch directory structure is inconvenient

### ISSUE THREAD

**Issue by xmclark** [CachedNerds/Hatch#71]
The structure puts the main hatch source files in /Hatch/hatch. This makes CI configuration inconvenient. It also requires that we have two different gitignore files.

**Comment by xmclark** [comment]
A natural solution is moving everything to the top level directory. 

The logo could be moved to a different repo or a sub directory.

**Comment by technetos** [comment]
No.  We have taken care of the CI handling already.  There is more to a project than just the code for its implementation.  The directory structure for hatch at the top level and Hatch/hatch is perfectly fine.

**Comment by DannyPeck** [comment]
It does complicate the CI by having to use a custom script just to enter the directory.

**Comment by technetos** [comment]
Its fine.  CI is implemented and there is literally nothing that changes.  It just works.

**Comment by xmclark** [comment]
So I think the extra script does complicate it. The default script that runs for rust projects on travis run the exact commands we run, without the extra shell script. I do think there is a way to avoid having a script at all. I have to give it first though.

**Comment by technetos** [comment]
Why does it matter? Travis runs whatever we tell it to run and that process succeeds or fails and is reported back to GitHub.

**Comment by xmclark** [comment]
It is a cleanliness matter. Travis gives us everything we need in the Travis.yml file. Maintaining an extra script seems unnecessary.

Additionally, I think the directory structure mat be the reason @DannyPeck has an issue getting coveralls working. I think coveralls expects the rust cargo file in the top directory.

**Comment by technetos** [comment]
Ive removed the travis ci_helper script.
 
As for coveralls we should read this:
https://github.com/huonw/travis-cargo#coveralls

And as far as your claim that one directory path is breaking coveralls, all you do is add the following before all their other commands in the script section: `cd hatch &&`

Its not a cleanliness **problem**, a project has documentation and other artifacts other than the implementation of the code, doing it this way **is** cleanliness.

**Comment by xmclark** [comment]
You're right.
