### ISSUE TITLE
Setup build and code coverage badges to reflect current branch

### ISSUE THREAD

**Issue by xmclark** [CachedNerds/Hatch#77]
The badges on the readme are currently hard coded. An automated process should be setup to change the readme so that the badges reflect the current branch.

**Comment by xmclark** [comment]
I think a good solution for this is writing a web service to do the post merge readme update commit.

**Comment by technetos** [comment]
What an idea

https://rocket.rs/

**Comment by xmclark** [comment]
@technetos we could make the web service a child project. But it seems general enough that it could be its own repo. It seems like updating travis badges could be something lots of projects need.

**Comment by technetos** [comment]
I agree, completely separate repo.

**Comment by xmclark** [comment]
I think that writing a webhook to do make an automatic commit may not go over well with github. I was reading that they are opposed universally to bots as they want to maintain the humanity of github. I think the best option at this point is maintaining two sections of badges. One for dev and one for master.
