### ISSUE TITLE
Refactor some sections of recently developed code into their own modules

### ISSUE THREAD

**Issue by technetos** [CachedNerds/Hatch#84]
1. Make a platform module and move `task::platform_type`, `task::architecture` and `project::Arch` into that module
2. Make a locations module and move `deps::modules_path` and `deps::hatchfile_path` into that module
3. Move `project::Dependency` into `deps/dependency.rs`
4. Convert `project.rs` into `project/mod.rs` and move `project::BuildConfig` and `project::Target` into that module as `project::build::Config` and `project::build::Target` within the project module.

**Comment by DannyPeck** [comment]
After some discussion, we should move the project::BuildConfig to project::build::Config.
