### ISSUE TITLE
Add git support

### ISSUE THREAD

**Issue by technetos** [CachedNerds/Hatch#9]
As a user I want to be able to import an existing project from github using the project url.  

Repository: [git2-rs](https://github.com/alexcrichton/git2-rs)
Documentation: [git2-rs](https://docs.rs/git2/0.6.8/git2/)

Cloned repositories should be put in a directory called: modules

**Comment by xmclark** [comment]
I think I'm in favor of namespacing the directory by calling it "hatch_modules" instead. Discussion is welcome on this.

**Comment by technetos** [comment]
Fine with me

**Comment by xmclark** [comment]
Is adding a cli command out of scope of this ticket? Or should it be library only functionality for now?

I'm not up to speed on what we want the typical workflow in Hatch to be. @technetos what are your thoughts?

Off the top of my head, this kind of workflow for Hatch seems ok:
1. `git clone my-hatch-proj.git`
2. `cd my-hatch-proj`
3. `hatch update`
4. `hatch build`
5. `hatch run`
5. `hatch deploy`

Fetching dependencies would be in the `hatch update` step (or whatever keyword we decide to use). I could write a command that goes ahead and grabs all dependencies by using git2-rs.

**Comment by technetos** [comment]
~this conflicts with the current structure of Toolbox as it stands now~
